### ISSUE TITLE
Question regarding installation on macOS/Linux

### ISSUE THREAD

**Issue by Jaguar-515** [iranathan/robloxapi#15]
I'm not a macOS/Linux user, but I'm just wondering, how would you install this module?

**Comment by sbhadr** [comment]
Same way you would with windows. However, it may be under ``pip3`` or ``python3`` instead of ``pip`` and ``python``.

**Comment by iranathan** [comment]
Although a lot of people use this lib on windows the lib has been made on a Mac.

**Comment by Pythonic-Rainbow** [comment]
You can install a development version by https://github.com/iranathan/robloxapi#install-command

You can also install a version that developers pushed to the official Python Package site, which is usually more stable. I think most people should use this:

```
# *NIX
pip3 install robloxapi
# Windows
pip install robloxapi
```
