### ISSUE TITLE
....

### ISSUE THREAD

**Issue by dxdejong** [iranathan/robloxapi#19]
....

**Comment by Dionysusnu** [comment]
This is completely unrelated to this library. First of all, this is python, not node.js, second, you're not even mentioning a library. Please clarify what library you're using and send a snippet of your code. Or join the Roblox API support server: discord.gg/EDXNdAT

**Comment by dxdejong** [comment]
.....
I was just hoping he maybe knew why it wasn't working..
I didn't have any other way to contact him than trough an issue so I did..
sorry for trying god damn

**Comment by Dionysusnu** [comment]
You didn't even state what you were doing.... How the hell were we supposed to help. Also, there are other ways to contact him, for example the server I linked.

**Comment by iranathan** [comment]
I would be happy to help you, If you join the server and ask your question in the #api me or someone else will help you.

**Comment by dxdejong** [comment]
The server invite link is invalid, tried to join :/

**Comment by Dionysusnu** [comment]
I've edited it in the original comment. Now it's valid

**Comment by dxdejong** [comment]
I see it now, thank you.
