### ISSUE TITLE
Epic suggest

### ISSUE THREAD

**Issue by K4K4SH11** [iranathan/robloxapi#20]
Yes iranathan make it an array that returns user gamepass booleans :D

**Comment by iranathan** [comment]
```PY
[True, True, True, True, True]
```
there you go

**Comment by K4K4SH11** [comment]
Noob no as in
3 ways

A) function to get all gamepasses the user has
B) function to check whether user has gamepass by id

get braincell get to work

**Comment by K4K4SH11** [comment]
You made it and now is happy
😁

**Comment by iranathan** [comment]
#
