### ISSUE TITLE
rbx.Auth.login() outputs False

### ISSUE THREAD

**Issue by xDsquare** [iranathan/robloxapi#3]
```
import robloxapi

rbx = robloxapi.client()
print(rbx.Auth.login("_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_..."))
```

I can confirm that the session is valid, but it outputs "False".
Maybe they changed something, because I already tried other APIs and it didn't worked neither.

**Comment by iranathan** [comment]
You should use this 

```
import robloxapi

rbx = robloxapi.client('_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_...')
```
Auth class might not work. 
If that does not work check your cookie.

**Comment by iranathan** [comment]
Oh. I already see what's wrong with the rbx.Auth.Login function Thank you!
I will push an update fixing it soon.

**Comment by xDsquare** [comment]
Alright, thank you man. :)

**Comment by xDsquare** [comment]
I'm sorry but I need to ask you something offtopic.:
Is it possible to pay/send robux to other users without loss with this API?

**Comment by iranathan** [comment]
Yes, Sorry I have not made docs for most of the package yet.

you can do payouts with:
```
rbx.Group.groupPayout(groupid, userid, amount)
```

**Comment by xDsquare** [comment]
Thank you for the quick fix, but I'm still getting an error (#a296a75).

```
>>> print(rbx.Auth.login("_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_..."))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/robloxapi/Auth.py", line 18, in login
    return client(cookie)
NameError: name 'client' is not defined
```

**Comment by xDsquare** [comment]
Okay thank you very much. I managed to login with this fix.:

> You should use this
> 
> ```
> import robloxapi
> 
> rbx = robloxapi.client('_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_...')
> ```
> 
> Auth class might not work.
> If that does not work check your cookie.

[rbx.Auth.login() is unfortunately still not working for me.](https://github.com/iranathan/robloxapi/issues/4)


Do you know if it's possible to transfer funds from my account to group funds?

**Comment by iranathan** [comment]
Yes, With the buyAsset function in the Asset class
