### ISSUE TITLE
Typo in IsUsenameTaken, should be IsUsernameTaken

### ISSUE THREAD

**Issue by Jaguar-515** [iranathan/robloxapi#7]
In [Auth.py](https://github.com/iranathan/robloxapi/blob/master/robloxapi/Auth.py), there is a typo in IsUsenameTaken.
This should be IsUsernameTaken.
**Old Code**
`...`
`def IsUsenameTaken(self, username):`
`...`
**New Code**
`...`
`def IsUsernameTaken(self, username):`
`...`

**Comment by iranathan** [comment]
👌 thanks. I will add soon.

**Comment by sbhadr** [comment]
https://github.com/iranathan/robloxapi/pull/8

**Comment by iranathan** [comment]
Sanjay fixed it!!!!

**Comment by Jaguar-515** [comment]
Thanks for the quick response!

**Comment by sbhadr** [comment]
#BlameIra
