### ISSUE TITLE
NameError: name 'json' is not defined

### ISSUE THREAD

**Issue by Jaguar-515** [iranathan/robloxapi#9]
I am getting a name error with this code:
```
import robloxapi
rbx = robloxapi.client()
print(rbx.Auth.IsUsernameTaken("Roblox"))
```

Error:
```
line 28, in IsUsernameTaken
if json.loads(r)['code'] == 0:
NameError: name 'json' is not defined
```

**Comment by iranathan** [comment]
Hello, Thank you for reporting this error.

This is not a problem. with the lib. It's because the stable version (on pypi) has not been updated yet.

But, Due to this being a real problem. I will leave this open till I update pypi.

Thanks, Ira.

**Comment by Jaguar-515** [comment]
Any updates to this?

**Comment by Jaguar-515** [comment]
hello @iranathan, you still here?

**Comment by sbhadr** [comment]
That’s an internal import issue.

**Comment by iranathan** [comment]
This has been fixed in the pypi project.

```PY
>>> import robloxapi
>>> rbx=robloxapi.client()
>>> rbx.Auth.IsUsernameTaken('roblox')
True
```

To install the update do: `pip install robloxapi -U`

Thanks, Ira.
